# Generated by Django 3.0.5 on 2020-07-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ordertemp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordertemp',
        ),
    ]
